<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDiscountCriteriasProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection(config('ecommerce.database_connection_name'))
            ->create(
                'ecommerce_discount_criterias_products',
                function(Blueprint $table) {
                    /** @var $table \Illuminate\Database\Schema\Blueprint */
                    $table->integer('discount_criteria_id')->index();
                    $table->integer('product_id')->index();
                    // autogenerated primary key name is too long:
                    /*
                    Identifier name 'ecommerce_discount_criterias_products_discount_criteria_id_product_id_primary' is too long (SQL: alter table `ecommerce_discount_criterias_products` add primary key `ecommerce_discount_criterias_products_discount_criteria_id_product_id_primary`(`discount_criteria_id`, `product_id`))
                    */
                    $table->primary(['discount_criteria_id', 'product_id'], 'ecommerce_discount_criterias_products_dci_pi_primary');
                }
            );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ecommerce_discount_criterias_products');
    }
}
