<?php

namespace Railroad\Ecommerce\Factories;

use Faker\Generator;
use Railroad\Ecommerce\Services\ConfigService;
use Railroad\Ecommerce\Services\ProductService;


class ProductFactory extends ProductService
{
    /**
     * @var Generator
     */
    protected $faker;

    public function store(
        $brand = '',
        $name = '',
        $sku = '',
        $price = 0,
        $type = '',
        $active = 0,
        $description = '',
        $thumbnail_url = null,
        $is_physical = 0,
        $weight = 0,
        $subscription_interval_type = null,
        $subscription_interval_count = null,
        $stock = 0)
    {
        $this->faker = app(Generator::class);

        $parameters =
            func_get_args() + [
                ConfigService::$brand,
                $this->faker->word,
                $this->faker->word,
                $this->faker->numberBetween(1, 2000),
                $this->faker->randomElement(
                    [
                        ProductService::TYPE_PRODUCT,
                        ProductService::TYPE_SUBSCRIPTION
                    ]
                ),
                $this->faker->boolean,
                $this->faker->text,
                $this->faker->url,
                $this->faker->boolean,
                $this->faker->numberBetween(1, 2000),
                null,
                null,
                $this->faker->numberBetween(0, 1000)
            ];
        //  dd($parameters);
        return parent::store(...$parameters);


        //return parent::store($brand, $name, $sku, $price, $type, $active, $description, $thumbnail_url, $is_physical, $weight, $subscription_interval_type, $subscription_interval_count, $stock); // TODO: Change the autogenerated stub
    }
}